name: reidha.github.io

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to reidha.github.io
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git log --oneline -10
          npm run build
          npm run export
          cd reidha.github.io
          git init
          git remote add origin git@github.com:reidha/reidha.github.io.git
          git config user.name "reidha"
          git config user.email "kdaimon.8@gmail.com"
          git add -A
          git commit -m auto
          git push -f origin master